apiVersion: v1
kind: Service
metadata:
  name: replicated-premkit
  labels:
    app: replicated
    tier: premkit
spec:
  type: ClusterIP
  selector:
    app: replicated
    tier: premkit
  ports:
  - name: https
    protocol: TCP
    port: 9880
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: replicated-premkit-tls
data:
  key.pem: |
    {{ premkit_tls_key }}
  cert.pem: |
    {{ premkit_tls_cert }}
---
{% include 'kubernetes/premkit-pvc.yml' %}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: replicated-premkit
  labels:
    app: replicated
    tier: premkit
spec:
  template:
    metadata:
      labels:
        app: replicated
        tier: premkit
    spec:
      containers:
      - name: premkit
        image: "premkit/premkit:1.1.0"
        env:
        - name: PREMKIT_BIND_HTTP
          value: "0"
        - name: PREMKIT_BIND_HTTPS
          value: "9880"
        - name: PREMKIT_SELF_SIGNED
          value: "false"
        - name: PREMKIT_KEY_FILE
          value: /tls/key.pem
        - name: PREMKIT_CERT_FILE
          value: /tls/cert.pem
        - name: LOG_LEVEL
          value: "{{ log_level|default('info', true) }}"
        ports:
        - name: http
          protocol: TCP
          containerPort: 9880
        securityContext:
          seLinuxOptions:
            type: {{ selinux_replicated_domain }}
        volumeMounts:
        - name: premkit-tls-volume
          readOnly: true
          mountPath: /tls
      volumes:
      - name: premkit-tls-volume
        configMap:
          name: replicated-premkit-tls
