apiVersion: v1
kind: Service
metadata:
  name: replicated-lb
  labels:
    app: replicated
    tier: master
spec:
  type: {{ service_type | default('LoadBalancer', true) }}
  selector:
    app: replicated
    tier: master
  ports:
  - name: replicated-ui
    port: 8800
    protocol: TCP
