---
apiVersion: v1
kind: List
items:
  - metadata:
      labels:
        name: weave-net
      name: weave-net
      annotations:
        cloud.weave.works/launcher-info: |-
          {
            "server-version": "master-9eec4bc",
            "original-request": {
              "url": "/k8s/v1.6/net?v=v1.9.4",
              "date": "Sun Apr 16 2017 13:47:55 GMT+0000 (UTC)"
            },
            "email-address": "support@weave.works"
          }
    apiVersion: v1
    kind: ServiceAccount
  - metadata:
      labels:
        name: weave-net
      name: weave-net
      annotations:
        cloud.weave.works/launcher-info: |-
          {
            "server-version": "master-9eec4bc",
            "original-request": {
              "url": "/k8s/v1.6/net?v=v1.9.4",
              "date": "Sun Apr 16 2017 13:47:55 GMT+0000 (UTC)"
            },
            "email-address": "support@weave.works"
          }
    spec:
      template:
        metadata:
          labels:
            name: weave-net
        spec:
          tolerations:
            - key: node-role.kubernetes.io/master
              effect: NoSchedule
          containers:
            - name: weave
              image: 'weaveworks/weave-kube:1.9.4'
              imagePullPolicy: Always
              command:
                - /home/weave/launch.sh
              env: []
              livenessProbe:
                initialDelaySeconds: 30
                httpGet:
                  host: 127.0.0.1
                  path: /status
                  port: 6784
              volumeMounts:
                - name: weavedb
                  mountPath: /weavedb
                - name: cni-bin
                  mountPath: /host/opt
                - name: cni-bin2
                  mountPath: /host/home
                - name: cni-conf
                  mountPath: /host/etc
                - name: dbus
                  mountPath: /host/var/lib/dbus
                - name: lib-modules
                  mountPath: /lib/modules
              resources:
                requests:
                  cpu: 10m
              securityContext:
                privileged: true
            - name: weave-npc
              image: 'weaveworks/weave-npc:1.9.4'
              imagePullPolicy: Always
              resources:
                requests:
                  cpu: 10m
              securityContext:
                privileged: true
          volumes:
            - name: weavedb
              emptyDir: {}
            - name: cni-bin
              hostPath:
                path: /opt
            - name: cni-bin2
              hostPath:
                path: /home
            - name: cni-conf
              hostPath:
                path: /etc
            - name: dbus
              hostPath:
                path: /var/lib/dbus
            - name: lib-modules
              hostPath:
                path: /lib/modules
          hostPID: true
          hostNetwork: true
          serviceAccountName: weave-net
          restartPolicy: Always
          securityContext:
            seLinuxOptions:
              type: spc_t
    apiVersion: extensions/v1beta1
    kind: DaemonSet
  - metadata:
      labels:
        name: weave-net
      name: weave-net
      annotations:
        cloud.weave.works/launcher-info: |-
          {
            "server-version": "master-9eec4bc",
            "original-request": {
              "url": "/k8s/v1.6/net?v=v1.9.4",
              "date": "Sun Apr 16 2017 13:47:55 GMT+0000 (UTC)"
            },
            "email-address": "support@weave.works"
          }
    rules:
      - apiGroups:
          - ''
        resources:
          - pods
          - namespaces
          - nodes
        verbs:
          - get
          - list
          - watch
      - apiGroups:
          - extensions
        resources:
          - networkpolicies
        verbs:
          - get
          - list
          - watch
    apiVersion: rbac.authorization.k8s.io/v1beta1
    kind: ClusterRole
  - metadata:
      labels:
        name: weave-net
      name: weave-net
      annotations:
        cloud.weave.works/launcher-info: |-
          {
            "server-version": "master-9eec4bc",
            "original-request": {
              "url": "/k8s/v1.6/net?v=v1.9.4",
              "date": "Sun Apr 16 2017 13:47:55 GMT+0000 (UTC)"
            },
            "email-address": "support@weave.works"
          }
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: weave-net
    subjects:
      - kind: ServiceAccount
        name: weave-net
        namespace: kube-system
    apiVersion: rbac.authorization.k8s.io/v1beta1
    kind: ClusterRoleBinding
